name: full_picker_example
description: A new Flutter project for full picker example
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  full_picker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true