name: ahille
description: Ahille project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chatview:
    path: chatview

  flutter_localizations:
    sdk: flutter

  # Language
  intl: ^0.17.0

  # BloC design pattern
  flutter_bloc: ^8.0.1

  shared_preferences: ^2.0.15

  # Multi Theme
  adaptive_theme: ^3.1.1

  # Parse Server SDK
  parse_server_sdk_flutter: ^3.1.3

  timezone: ^0.8.0

  # Toast
  oktoast: ^3.2.0

  persian_datetime_picker: ^2.4.0

  responsive_framework: ^0.2.0

  responsive_sizer: ^3.1.0
  provider: ^6.0.3
  equatable: ^2.0.3
  rules: ^2.0.0
  lazy_load_scrollview: ^1.3.0
  cached_network_image: ^3.2.1

  video_compress: ^3.1.1
  path_provider: ^2.0.11
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true
  assets:
    - assets/images/.
    - assets/lottie/.

  fonts:
    - family: IRANSans
      fonts:
        - asset: fonts/iran_sansx_medium.ttf

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_intl:
  enabled: true
  main_locale: en
