name: ahille
description: Ahille project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chatview:
    path: chatview

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15

  adaptive_theme: ^3.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true

  assets:
    - assets/images/.
    - assets/lottie/.

  fonts:
    - family: IRANSans
      fonts:
        - asset: fonts/iran_sans_num_medium.ttf

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_intl:
  enabled: true
  main_locale: en
