name: full_picker
description: A Flutter package that helps you select files in different modes.
version: 1.3.6
homepage: https://github.com/mbfakourii/full_picker
repository: https://github.com/mbfakourii/full_picker
issue_tracker: https://github.com/mbfakourii/full_picker/issues

topics:
  - picker
  - camera
  - cropper
  - compressor
  - record

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  # Camera
  camera: ^0.10.5+5

  # Path
  path_provider: ^2.1.1

  # Toast
  fluttertoast: ^8.2.3

  # Crop
  image_cropper: ^5.0.0

  # File Picker
  file_picker: ^6.1.1

  # Compressor Video
  light_compressor: ^2.2.0

  # Recorder
  record: ^4.4.4

  # Stop watch timer
  stop_watch_timer: ^3.0.2

  # Http
  http: ^1.1.0

  # Uuid
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: full_picker
      ios:
        default_package: full_picker
      linux:
        default_package: full_picker
      macos:
        default_package: full_picker
      web:
        default_package: full_picker
      windows:
        default_package: full_picker

screenshots:
  - description: Full Picker logo.
    path: screenshots/logo.png