name: full_picker
description: A Flutter package that helps you select files in different modes
version: 1.2.0
homepage: https://github.com/mbfakourii/full_picker
issue_tracker: https://github.com/mbfakourii/full_picker/issues
repository: https://github.com/mbfakourii/full_picker

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=2.19.1"

dependencies:
  flutter:
    sdk: flutter

  # Camera
  camera: ^0.10.4

  # Path
  path_provider: ^2.0.12

  # Toast
  fluttertoast: ^8.1.2

  # Crop
  image_cropper: ^3.0.1
  video_player: any

  # File Picker
  file_picker: ^5.2.5

  # Compressor Video
  light_compressor: ^2.0.1

  # Recorder
  record: ^4.4.4

  # Stop watch timer
  stop_watch_timer: ^2.0.0

  # Http
  http: ^0.13.5

  # Uuid
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: full_picker
      ios:
        default_package: full_picker
      linux:
        default_package: full_picker
      macos:
        default_package: full_picker
      web:
        default_package: full_picker
      windows:
        default_package: full_picker