name: full_picker
description: A Flutter package that helps you select files in different modes.
version: 1.3.5
homepage: https://github.com/mbfakourii/full_picker
issue_tracker: https://github.com/mbfakourii/full_picker/issues
repository: https://github.com/mbfakourii/full_picker

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  # Camera
  camera: ^0.10.5+3

  # Path
  path_provider: ^2.1.0

  # Toast
  fluttertoast: ^8.2.2

  # Crop
  image_cropper: ^5.0.0

  # File Picker
  file_picker: ^5.3.3

  # Compressor Video
  light_compressor: 2.0.1

  # Recorder
  record: ^4.4.4

  # Stop watch timer
  stop_watch_timer: ^3.0.1

  # Http
  http: ^1.1.0

  # Uuid
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        default_package: full_picker
      ios:
        default_package: full_picker
      linux:
        default_package: full_picker
      macos:
        default_package: full_picker
      web:
        default_package: full_picker
      windows:
        default_package: full_picker

screenshots:
  - description: Full Picker logo.
    path: screenshots/logo.png