name: full_picker
description: A flutter package that helps you in selecting files
version: 1.0.0
homepage: https://github.com/mbfakourii/full_picker
issue_tracker: https://github.com/mbfakourii/full_picker/issues
repository: https://github.com/mbfakourii/full_picker

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.17.6"

dependencies:
  flutter:
    sdk: flutter

  responsive_sizer: ^3.1.0
  camera: ^0.10.0+1

  path_provider: ^2.0.11
  fluttertoast: ^8.0.9

  # Permission Handler
  permission_handler: ^9.2.0

  # Crop
  image_cropper: ^3.0.0

  # File Picker
  file_picker: ^4.0.0
  light_compressor: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  plugin:
    platforms:
      android:
        default_package: full_picker
      ios:
        default_package: full_picker
      linux:
        default_package: full_picker
      macos:
        default_package: full_picker
      web:
        default_package: full_picker
      windows:
        default_package: full_picker